<?php
// $Id: opensoft.module Exp $


function opensoft_mailing_form($form, &$form_state) {
    $form['name'] = array(
        '#type' => 'textfield',
        '#required' => true,
        '#size' => '26',
        '#attributes' => array(
            'placeholder' => 'ваше имя'
        )
    );
    $form['email'] = array(
        '#type' => 'textfield',
        '#required' => true,
        '#size' => '26',
        '#attributes' => array(
            'placeholder' => 'ваш e-mail'
        )
    );
    $form['submit'] = array(
        '#type' => 'image_button',
        '#button_type' => 'submit',
        '#value' => t('Подписаться'),
        '#src' => 'sites/all/themes/generation_plus/images/subscription.png'
    );
    return $form;
}

function opensoft_mailing_form_validate($form, &$form_state) {
    // Validation logic.
}
function opensoft_mailing_form_submit($form, &$form_state) {
    // Submission logic.
}
